https://desktopgames.com.ua/ua/

katalog_button = "//div[@class='category_show']"
search_element = "//div[@id='hd_middle']/descendant::input[@id='autocomplete']"
search_button = "//div[@id='hd_middle']/descendant::input[@title='найти']"
adress_button = "//i[@class='fas fa-map-marker-alt']/ancestor::a"
banner = "//div[@id='slick-slide01']/descendant::img[@loading='lazy']"
our_localization_button = "//*[text()= 'Наші локалізації']"
wishlist_button = "//*[@id='hd_middle']/span"
catalog_button = "//*[@id='menu_category_slim']/child::*"
newarrivals_button = "//div[@class='main-news']/child::a[@rel='nofollow' and @title='Новинки']"
busket_button = "//*[@id='cart_div_element']"
my_order = "//*[text()= 'Моє замовлення']"
for_two = "//*[text()= 'Для двох']"
alias_button = "//li/*[contains(text(), 'Alias')]"
accsesories_button = "//span/a[contains(text(), 'Аксесуари')]"
club_button = "//span/a[@target='_blank']"
free_shiping = "//div[@class='info_article_main']"
payment_info = "//*[contains(text(), 'Visa')]"
dixit_button = "//ul[@class='main_article']//*[contains(text(), 'Dixit')]"
preorder_button = "//*[@ref='27']"
top_button = "//*[@class='seltab']"
ticket_to_ride_button = "//*[@class='footer_block']//*[contains(text(), 'Ticket')]"
phone_button = "/*[@class='footer_block']//*[contains(text(), '(067) 589-03-97')]"
mail_button = "//*[@class='footer_block']//*[contains(text(), 'opt@igromag.ua')]"
fb_button = "//*[@title='Facebook']/child::*"
instagram_button = "//*[@title='instagram']/child::*"
telegram_button = "//*[@title='telegram']/child::*"
youtube_button = "//*[@title='youtube']/child::*"
tiktok_button = "//*[@title='tiktok']/child::*"
chat_button = "//button[@aria-label='chats-button']"
i_sae_that_button = "//*[@class='popup_up_v']"


katalog_button = ".category_show]"
search_element = "#search_submit #autocomplete"
search_button = "#search_submit > input.search_btn"
adress_button = ".head_cont_desk > .location"
banner = "#slick-slide02 > div > div > a > img"
our_localization_button = "[title= 'Наші локалізації']"
wishlist_button = "#hd_middle > span"
catalog_button = "#menu_category_slim > div"
newarrivals_button = "[class='main-news'] > [title='Новинки']"
busket_button = "#cart_div_element"
